<html>
<head>
    <title>Libray Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h5 style="background-color: greenyellow;"><strong>Book details</strong></h5>
<p style="text-primary">ISBN number: <?=$book->getBook_isbn()?></strong></p>
<p>Name: <?=$book->getBook_name()?></p>
<p>Category: <?=$book->getBook_category()?></p>

</body>
</html>

