<html>
<head>
    <title>Library Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Book</h1>

<form class="pure-form" method="post" action="/book/new">

    
    <label for="isbn">Book_ISBN</label>
    <textarea name="isbn" id="isbn" rows="1" cols="10"></textarea><br />
    
    <label for="name">Book_Name</label>
    <textarea name="name" id="name" rows="1" cols="10"></textarea><br />

    <label for="category">Book_category</label>
    <textarea name="category" id="category" rows="1" cols="10"></textarea><br />
  
<?php

?>
    </select><br />

    <input type="submit" class="pure-button btn-primary" value="Create" />
</form>

</body>
</html>


